openapi: 3.0.0
info:
  title: DevOps_in_a_nutshell
  version: 1.0.0
servers:
  - url: http://{{base_url}}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: release_acceptance_test
paths:
  /login:
    post:
      tags:
        - release_acceptance_test
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: '{{username}}'
                password: '{{password}}'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /shorturl:
    post:
      tags:
        - release_acceptance_test
      summary: Create a new short URL
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                long_url: '{{long_url}}'
      security:
        - bearerAuth: []
      responses:
        '201':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - release_acceptance_test
      summary: Get all short URL
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /shorturl/{short_url}:
    get:
      tags:
        - release_acceptance_test
      summary: Redirect to long URL
      parameters:
        - name: short_url
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - release_acceptance_test
      summary: Delete a short URL
      security:
        - bearerAuth: []
      parameters:
        - name: short_url
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
